### ISSUE TITLE
Int Strenght (replaces the random value added to the atk)

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#12]
Instead of the random value which is now added each time the hero attacks(, it will be replaced as the value added to the atk). Therefore realatk = atk + ( random 0 bis "strenght" ) .
Strenght can be upgraded or added when u get the right items.

**Comment by Red-Pi** [comment]
Maybe the strength should be linked to the upcoming classes feature.

**Comment by Kapejko** [comment]
Sure thing, so the strenght will depend on the choosen class

**Comment by Red-Pi** [comment]
Basic Implementation is in branch, will be merged to master later

**Comment by Red-Pi** [comment]
Merged to master - Done
