### ISSUE TITLE
Add a "Matrix" Map to the Project

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#13]
An Map should be added. As an example when the hero chooses to go 4 times 'left', he will be in the same room as before. Likewise when he ecounter a shopkeeper in room '3' and he goes 4 times 'right' he will ecounter the same shop again.
Add an command to go 'back' but with a possibility to trip, loose an item, trigger a trap or ecounter a monster.

**Comment by Red-Pi** [comment]
The concept was done in merge #62 
New tasks for implementation: #63, #64, #65
