### ISSUE TITLE
Addition of classes

### ISSUE THREAD

**Issue by Red-Pi** [Red-Pi/KDC-Base#15]
Adding Classes with different stats.
Knight (Higher ATK, Lower Agility), Mage (Weaker ATK, but special ATK), Barbarian (More Strength), Ninja/Assasin (Higher Agility, Fleeing might be possible), ...

**Comment by Kapejko** [comment]
:O hast du schon so viel gemacht?

**Comment by Kapejko** [comment]
Oh XD I see, well then I will do it today, great ideas by the way

**Comment by Red-Pi** [comment]
Done by @Kapejko in #40
