### ISSUE TITLE
BUG: No Lose Condition after rest

### ISSUE THREAD

**Issue by Red-Pi** [Red-Pi/KDC-Base#27]
**Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 4**
 **Keks tries to rest
 Suddenly Keks hear something, therefore he wake up and prepare to face it**

 A Skeleton jumps out of nowhere and blocks the way
 It seems suprised

       .-.
      (o.o)
       |O|
      __|__
  \  /.=|=.\  /
   \/ .=|=. \/
      .=|=.
      (_=_)
     (:| |:)
      || ||
      () ()
      || ||
      || ||
     ==' '==

 START OF ROUND : 1
 HP : 7 ÔÖÑ      ATK : 4-6 ÔÜö      DEF : 1 Ôø¿
 Monster HP : 9 MÔÖÑ      Monster ATK : 3-5 MÔÜö
 Heal potions left : 0

 The Skeleton is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 1
 The Skeleton evaded your attack!
 The Skeleton hits Keks for : 4
 Keks's armor absorbed 1 damage
 Keks's armor is damaged, but it didnt break yet
 Keks recieved : 3 damage

 START OF ROUND : 2
 HP : 4 ÔÖÑ      ATK : 4-6 ÔÜö      DEF : 1 Ôø¿
 Monster HP : 9 MÔÖÑ      Monster ATK : 3-5 MÔÜö
 Heal potions left : 0

 The Skeleton is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 2
 Keks hits the Skeleton for : 6
 The Skeleton hits Keks for : 4
 Keks's armor absorbed 1 damage
 A piece of Keks's armor was destroyed by the attack
 Keks recieved : 3 damage

 START OF ROUND : 3
 HP : 1 ÔÖÑ      ATK : 4-6 ÔÜö      DEF : 0 Ôø¿
 Monster HP : 3 MÔÖÑ      Monster ATK : 3-5 MÔÜö
 Heal potions left : 0

 The Skeleton is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 3
 Keks hits the Skeleton for : 6
 The Skeleton hits Keks for : 4
 Keks recieved : 4 damage
 Keks triggered a hidden trap, it hits him for 2 damage

 **HP : -5 ÔÖÑ**      ATK : 4-6 ÔÜö      DEF : 0 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 **What should Keks do?**
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 1

**Comment by Kapejko** [comment]
What happend here, the player goes into -hp?

**Comment by Kapejko** [comment]
We need to do a while(hp<=0) around the whole thing
And the rest option is choosen as much as the player wants to because he can rest in a room as often as he her needs to so when the hero rests he her can choose "choices()" again

**Comment by Red-Pi** [comment]
Fix merged to master - Done
