### ISSUE TITLE
Bug1 ( Anzahl von Monster stimmt nicht )

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#31]
Dude look at that output:
Am Ende
 RESULT OF ROUND : 6
 The ghost evaded his attack
 The Ghost hits Pasternak for : 5
 Pasternak's armor absorbed 3 damage
 A piece of Pasternak's armor was destroyed by the attack
 Pasternak recieved : 2 damage
 Pasternak died
 Pasternak defeated 18 vile creatures!!!
 1 Skeleton, 1 Spider, 1 Ghost

   _____                        _____
  |  __ \                      |  _  |
  | |  \/ __ _ _ __ ___   ___  | | | |_   _____ _ __
  | | __ / _` | '_ ` _ \ / _ \ | | | \ \ / / _ \ '__|
  | |_\ \ (_| | | | | | |  __/ \ \_/ /\ V /  __/ |
   \____/\__,_|_| |_| |_|\___|  \___/  \_/ \___|_|

 Press Enter to exit

**Comment by Red-Pi** [comment]
Well... we should look into that :D

**Comment by Red-Pi** [comment]
Can confirm.

 Keks died
 **Keks defeated 27 vile creatures!!!
 1 Skeleton, 1 Spider, 1 Ghost**

Apparently Monstertypes arent counted correctly.

I suspect it has something to do with #33 : When we start seaching we are probably stuck somewhere in the code.

I will take a look when I have the time.

**Comment by Red-Pi** [comment]
Embarrassing mistake on my side
Fix is merged to master
#dc26f23 commit

Done
