### ISSUE TITLE
Bug2 ( Why u get 2 Jack Daniels after defeating the second monster ??? )

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#32]
After defeating the second monster you get 2 jack daniels...

**Comment by Red-Pi** [comment]
I think I need more information than that :D
What is the output of the game?
What are the steps to get to this Bug?

**Comment by Red-Pi** [comment]
I couldn't reproduce this, sorry.

**Comment by Red-Pi** [comment]
Working on #33, #34 and #31 will probably fix this.

**Comment by Red-Pi** [comment]
Hopfully fixed with Merge #36 - please test

**Comment by Red-Pi** [comment]
Presumably fixed
