### ISSUE TITLE
BUG: Search is triggered at the wrong time

### ISSUE THREAD

**Issue by Red-Pi** [Red-Pi/KDC-Base#33]
HP : 25 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 17 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 5
 Keks triggered a hidden trap, it hits his for 2 damage

 HP : 23 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 17 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 4
 Keks tries to rest
 Nothing happend during the sleep
 Keks healed himself for 2 hitpoints

 HP : 25 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 17 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 1
 Keks went left
 A Skeleton jumps out of nowhere and blocks the way
 It seems suprised

       .-.
      (o.o)
       |O|
      __|__
  \  /.=|=.\  /
   \/ .=|=. \/
      .=|=.
      (_=_)
     (:| |:)
      || ||
      () ()
      || ||
      || ||
     ==' '==

 START OF ROUND : 1
 HP : 25 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 17 Ôø¿
 Monster HP : 9 MÔÖÑ      Monster ATK : 4-6 MÔÜö
 Health potions left : 2

 The Skeleton is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 1
 Keks hits the Skeleton for : 8
 The Skeleton hits Keks for : 5
 Keks's armor absorbed 17 damage
 Keks's armor is damaged, but it didnt break yet
 Keks recieved : 0 damage

 START OF ROUND : 2
 HP : 25 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 17 Ôø¿
 Monster HP : 1 MÔÖÑ      Monster ATK : 4-6 MÔÜö
 Health potions left : 2

 The Skeleton is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 2
 Keks hits the Skeleton for : 8
 The Skeleton hits Keks for : 5
 Keks's armor absorbed 17 damage
 A piece of Keks's armor was destroyed by the attack
 Keks recieved : 0 damage
 Keks found a heal potion
   |~|
  .'ÔÖÑ`.
  `._.'

 HP : 25 ÔÖÑ      ATK : 6-8 ÔÜö      DEF : 16 Ôø¿
 Possible actions: Go to another room, search this room, rest

Solution:
Rework the searching
Clearer fight starting

**Comment by Red-Pi** [comment]
Hopfully fixed with Merge #36 - please test

**Comment by Red-Pi** [comment]
NOT FIXED:

 RESULT OF ROUND : 3
 Keks hits the Spider for : 3
 Keks was quick and evaded the incoming attack!

 !!! Keks managed to anihilate the monster !!!

 HP : 13 ÔÖÑ      ATK : 3-5 ÔÜö      DEF : 0 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 5
 Keks found an poisonous snake
 Its moving towards Keks and its aware of his presence
 Keks could try to run away from it or stay and hope it will ignore his
 Enter 1(run), 2(stay) :
2
 Keks manages to get away from the snake

 HP : 13 ÔÖÑ      ATK : 3-5 ÔÜö      DEF : 0 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 4
 Keks tries to rest
 Suddenly Keks hears something, therefore he wakes up and prepares to face it

 Casper the ghost appears
 He looks spooky!
 ATTENTION: The ghost is capable to evade nearly any physical attack
        .-.
      .'   `.
      :g g   :
      : o    `.
     :         ``.
    :             `.
   :  :         .   `.
   :   :          ` . `.
    `.. :            `. ``;
       `:;             `:'
          :              `.
           `.              `.     .
             `'`'`'`---..,___`;.-'


 START OF ROUND : 1
 HP : 13 ÔÖÑ      ATK : 3-5 ÔÜö      DEF : 0 Ôø¿
 Monster HP : 2 MÔÖÑ      Monster ATK : 5-6 MÔÜö
 Health potions left : 1

 The Ghost is about to attack
 What should Keks do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 1
 Keks hits the Ghost for : 4
 The Ghost hits Keks for : 6
 Keks recieved : 6 damage
 Keks found a heal potion
   |~|
  .'ÔÖÑ`.
  `._.'

 HP : 7 ÔÖÑ      ATK : 3-5 ÔÜö      DEF : 0 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keks do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search):

**Comment by Kapejko** [comment]
Is it closed now?

**Comment by Red-Pi** [comment]
I haven't done any testing for a few days, so I don't know

**Comment by Red-Pi** [comment]
Not Fixed, probably linked to #69

**Comment by Red-Pi** [comment]
Probably fixed
