### ISSUE TITLE
Fragmentation of Initiate Fight?

### ISSUE THREAD

**Issue by Red-Pi** [Red-Pi/KDC-Base#42]
Maybe we should break the entrie fight sequence down to smaller blocks / functions, to improve working on them.

Also maybe rebuild the structure to have a clear priority for attacks, health potions etc.

**Comment by Red-Pi** [comment]
The question is: is this needed and helpful or not?

**Comment by Kapejko** [comment]
I agree about separate the fight sequence down to smaller blocks like
showstats()
monsteratk()
heroatk()
And what you mean by rebuilding the structure to have a clear priority?

**Comment by Kapejko** [comment]
Done?
