### ISSUE TITLE
BUG: Sleeping damaging player

### ISSUE THREAD

**Issue by Red-Pi** [Red-Pi/KDC-Base#43]
Enter 'm' for male or 'f' for female: f

 Time to name your Hero: Keksia
 These are the available classes:
 1(Knight), 2(Mage), 3(Barbarian), 4(Ninja), 5(Thief), 6(Taskmaster)
 Choose your hero's class: 3
 Your hero is a wild barbarian, who seeks brutal brawls and bloody fights
 Keksia is much stronger and can endure much longer than other heroes

 Welcome Keksia are you ready for an amazing adventure?
 Keksia starts her adventure with 45 HP, 2-8 ATK, 0 DEF,3 health potions
 A Skeleton jumps out of nowhere and blocks the way
 It seems suprised

       .-.
      (o.o)
       |O|
      __|__
  \  /.=|=.\  /
   \/ .=|=. \/
      .=|=.
      (_=_)
     (:| |:)
      || ||
      () ()
      || ||
      || ||
     ==' '==

 START OF ROUND : 1
 HP : 45       ATK : 2-8       DEF : 0
 Monster HP : 7       Monster ATK : 1-3 MÔÜö
 Health potions left : 3

 The Skeleton is about to attack
 What should Keksia do? Available options:
 Enter 1(attack), 2(defend), 3(flee), 4(use potion): 1

 RESULT OF ROUND : 1
 Keksia hits the Skeleton for : 7
 The Skeleton hits Keksia for : 3
 Keksia recieved : 3 damage

 !!! Keksia managed to anihilate the monster !!!

 HP : 42 ÔÖÑ      ATK : 2-8 ÔÜö      DEF : 0 Ôø¿
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keksia do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search):
5
 Keksia found a damn Jack Daniels bottle
           |~~~~|
           |    |
           |____|
           |    |
           (    )
           )    (
         .'      `.
        /          \
       |------------|
       |JACK DANIELS|
       |    ----    |
       |   (No.7)   |
       |    ----    |
       | Tennessee  |
       |  WHISKEY   |
       |  40% Vol.  |
       |------------|
       |____________|
 The heroes defense and attack raises by additional 2 points
 Possible actions: Go to another room, search this room, rest
 Available directions : 'left' , 'right' and 'forward'
 What should Keksia do?
 Enter 1(Go left), 2(Go Right), 3(Go forward), 4(Rest), 5(Search): 4
 Keksia tries to rest
 Nothing happend during the sleep
 **Keksia healed herself for -2 hitpoints**

**Comment by Red-Pi** [comment]
@Kapejko has fixed this in his branch, will be merged later

**Comment by Kapejko** [comment]
I have done it
