### ISSUE TITLE
Fragmentation of the whole code of Dooooooom

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#47]
Fragment some sections of the code, so it can be more clearer (OVERVIEWABILITIER) and easier so see through it when programming.

**Comment by Kapejko** [comment]
Isn't this issue the same as the one with the Title: "Offload the code to a second .cpp file" ?

**Comment by Red-Pi** [comment]
Yes this is linked to #25

**Comment by Red-Pi** [comment]
Done in Merge #56
