### ISSUE TITLE
Change all Attack() functions to ONE heroattack()

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#51]
Simplify the void(){ Attack } functions PLEASE

Like: heroattack( attackvalue )
{ Check rage, Check speedness, -> 
Check (if (realattackvalue - mdef)<=0)
{ realattackvalue = 0 ; Hero couldnt do any damage}
else 
{ mhp = mhp (realattackvalue) }
}

**Comment by Red-Pi** [comment]
Done in merge #57
