### ISSUE TITLE
It says, the hero defeates the dragon, even when he/she didn't

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#53]
URMOMGAY could stop his tail in the last moment and deals a quick blow with his weapon
 URMOMGAY is weak, even frail and couldn't stop the tail-attack from the dragon, he takes 5 damage
 Press enter to continue
 URMOMGAY died
 URMOMGAY defeated 21 vile creatures!!!
 3 Skeletons, 9 Spiders, 6 Ghosts, 2 Wolfs, 1 Dragon

   _____                        _____
  |  __ \                      |  _  |
  | |  \/ __ _ _ __ ___   ___  | | | |_   _____ _ __
  | | __ / _` | '_ ` _ \ / _ \ | | | \ \ / / _ \ '__|
  | |_\ \ (_| | | | | | |  __/ \ \_/ /\ V /  __/ |
   \____/\__,_|_| |_| |_|\___|  \___/  \_/ \___|_|

 Press Enter to exit

**Comment by Red-Pi** [comment]
Fixed in Merge #55
